language: php
sudo: false
before_install:
  - composer self-update
install:
  - composer update $COMPOSER_FLAGS --dev
matrix:
  include:
    - php: 5.4
      env: COMPOSER_FLAGS="--prefer-lowest"
    - php: 5.4
    - php: 5.5
    - php: 5.6
      script: phpunit --coverage-clover build/logs/clover.xml
      before_script:
        - mkdir -p build/logs
      after_script:
        - vendor/bin/test-reporter
    - php: 7.0
  fast_finish: true
