services:
    swagger.route_loader:
        class: KleijnWeb\SwaggerBundle\Routing\SwaggerRouteLoader
        arguments: [@swagger.document.repository]
        tags:
            - { name: routing.loader }

    swagger.serializer:
        class: KleijnWeb\SwaggerBundle\Serializer\SerializerAdapter
        arguments: [@swagger.serializer.array]

    swagger.serializer.array:
        class: KleijnWeb\SwaggerBundle\Serializer\ArraySerializer

    swagger.serializer.jms:
        class:   JMS\Serializer\Serializer\Serializer
        factory: [KleijnWeb\SwaggerBundle\Serializer\JmsSerializerFactory, factory]

    swagger.serializer.symfony:
        class:   JMS\Serializer\Serializer\SymfonySerializerFactory
        factory: [KleijnWeb\SwaggerBundle\Serializer\SymfonySerializerFactory, factory]

    swagger.document.repository:
        class: KleijnWeb\SwaggerBundle\Document\DocumentRepository
        arguments: [%swagger.document.base_path%]

    swagger.response.factory:
        class: KleijnWeb\SwaggerBundle\Response\ResponseFactory
        arguments: [@swagger.document.repository, @swagger.serializer]

    swagger.request.transformer:
        class: KleijnWeb\SwaggerBundle\Request\RequestTransformer
        arguments: [@swagger.request.transformer.content_decoder]

    swagger.request.transformer.content_decoder:
        class: KleijnWeb\SwaggerBundle\Request\Transformer\ContentDecoder
        arguments: [@swagger.serializer]

    kernel.listener.swagger.view:
        class: KleijnWeb\SwaggerBundle\EventListener\ViewListener
        arguments: [@swagger.response.factory]
        tags:
            - { name: kernel.event_listener, event: kernel.view, method: onKernelView }

    kernel.listener.swagger.exception:
        class: KleijnWeb\SwaggerBundle\EventListener\ExceptionListener
        arguments: [@logger]
        tags:
            - { name: kernel.event_listener, event: kernel.exception, method: onKernelException }

    kernel.listener.swagger.request:
        class: KleijnWeb\SwaggerBundle\EventListener\RequestListener
        arguments: [@swagger.document.repository, @swagger.request.transformer]
        tags:
            - { name: kernel.event_listener, event: kernel.request, method: onKernelRequest }

    # DEV
    swagger.dev.fixer.swagger_bundle_response:
        class: KleijnWeb\SwaggerBundle\Dev\DocumentFixer\Fixers\SwaggerBundleResponseFixer

    swagger.dev.command.amend_swagger:
        class: KleijnWeb\SwaggerBundle\Dev\Command\AmendSwaggerDocumentCommand
        arguments: [@swagger.document.repository, @swagger.dev.fixer.swagger_bundle_response]
        tags:
            -  { name: console.command }
