services:
  swagger.auth.key.jwt.authenticator:
      class:  KleijnWeb\SwaggerBundle\Security\Authenticator\JwtAuthenticator
      public: false

  swagger.auth.key.transient_user_provider:
      class: KleijnWeb\SwaggerBundle\Security\Transient\KeyUserProvider