services:
    swagger.dev.fixer.resource_definitions:
        class: KleijnWeb\SwaggerBundle\Dev\DocumentFixer\Fixers\ResourceDefinitionFixer

    swagger.dev.fixer.swagger_bundle_response:
        class: KleijnWeb\SwaggerBundle\Dev\DocumentFixer\Fixers\SwaggerBundleResponseFixer

    swagger.dev.command.amend_swagger:
        class: KleijnWeb\SwaggerBundle\Dev\Command\AmendSwaggerDocumentCommand
        arguments: ['@swagger.document.repository', '@swagger.dev.fixer.swagger_bundle_response']
        tags:
            -  { name: console.command }
